// This file will be auto-generated by Supabase CLI
// Run: pnpm db:generate-types
// For now, we define the types manually

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          display_name: string | null;
          email: string;
          avatar_url: string | null;
          target_language: string;
          native_language: string;
          level: 'beginner' | 'intermediate' | 'advanced';
          speaking_speed: number;
          voice_preference: string | null;
          timezone: string | null;
          gdpr_consent_at: string | null;
          marketing_consent: boolean;
          data_retention_consent: boolean;
          analytics_consent: boolean;
          third_party_sharing_consent: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          email: string;
          avatar_url?: string | null;
          target_language?: string;
          native_language?: string;
          level?: 'beginner' | 'intermediate' | 'advanced';
          speaking_speed?: number;
          voice_preference?: string | null;
          timezone?: string | null;
          gdpr_consent_at?: string | null;
          marketing_consent?: boolean;
          data_retention_consent?: boolean;
          analytics_consent?: boolean;
          third_party_sharing_consent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          email?: string;
          avatar_url?: string | null;
          target_language?: string;
          native_language?: string;
          level?: 'beginner' | 'intermediate' | 'advanced';
          speaking_speed?: number;
          voice_preference?: string | null;
          timezone?: string | null;
          gdpr_consent_at?: string | null;
          marketing_consent?: boolean;
          data_retention_consent?: boolean;
          analytics_consent?: boolean;
          third_party_sharing_consent?: boolean;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          language: string;
          level: string;
          topic: string | null;
          status: 'active' | 'completed' | 'archived';
          duration_seconds: number;
          total_tokens_used: number;
          user_words_spoken: number;
          ai_words_spoken: number;
          user_speaking_time_ms: number;
          ai_speaking_time_ms: number;
          silence_time_ms: number;
          interruptions_count: number;
          corrections_count: number;
          started_at: string;
          ended_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string | null;
          language: string;
          level: string;
          topic?: string | null;
          status?: 'active' | 'completed' | 'archived';
          duration_seconds?: number;
          total_tokens_used?: number;
          user_words_spoken?: number;
          ai_words_spoken?: number;
          user_speaking_time_ms?: number;
          ai_speaking_time_ms?: number;
          silence_time_ms?: number;
          interruptions_count?: number;
          corrections_count?: number;
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string | null;
          status?: 'active' | 'completed' | 'archived';
          duration_seconds?: number;
          total_tokens_used?: number;
          user_words_spoken?: number;
          ai_words_spoken?: number;
          user_speaking_time_ms?: number;
          ai_speaking_time_ms?: number;
          silence_time_ms?: number;
          interruptions_count?: number;
          corrections_count?: number;
          ended_at?: string | null;
        };
      };
      transcript_entries: {
        Row: {
          id: string;
          conversation_id: string;
          role: 'user' | 'assistant';
          content: string;
          audio_url: string | null;
          duration_ms: number | null;
          tokens_used: number | null;
          words_per_minute: number | null;
          confidence_score: number | null;
          language_detected: string | null;
          sentiment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role: 'user' | 'assistant';
          content: string;
          audio_url?: string | null;
          duration_ms?: number | null;
          tokens_used?: number | null;
          words_per_minute?: number | null;
          confidence_score?: number | null;
          language_detected?: string | null;
          sentiment?: string | null;
          created_at?: string;
        };
        Update: {
          content?: string;
          audio_url?: string | null;
          duration_ms?: number | null;
          tokens_used?: number | null;
          words_per_minute?: number | null;
          confidence_score?: number | null;
          language_detected?: string | null;
          sentiment?: string | null;
        };
      };
      conversation_tips: {
        Row: {
          id: string;
          conversation_id: string;
          category: 'grammar' | 'vocabulary' | 'pronunciation' | 'fluency' | 'general';
          content: string;
          examples: Json | null;
          original_text: string | null;
          corrected_text: string | null;
          priority: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          category: 'grammar' | 'vocabulary' | 'pronunciation' | 'fluency' | 'general';
          content: string;
          examples?: Json | null;
          original_text?: string | null;
          corrected_text?: string | null;
          priority?: number;
          created_at?: string;
        };
        Update: {
          category?: 'grammar' | 'vocabulary' | 'pronunciation' | 'fluency' | 'general';
          content?: string;
          examples?: Json | null;
          original_text?: string | null;
          corrected_text?: string | null;
          priority?: number;
        };
      };
      usage_records: {
        Row: {
          id: string;
          user_id: string;
          period_start: string;
          period_end: string;
          stt_minutes: number;
          tts_minutes: number;
          llm_input_tokens: number;
          llm_output_tokens: number;
          conversations_count: number;
          total_speaking_time_minutes: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          period_start: string;
          period_end: string;
          stt_minutes?: number;
          tts_minutes?: number;
          llm_input_tokens?: number;
          llm_output_tokens?: number;
          conversations_count?: number;
          total_speaking_time_minutes?: number;
          created_at?: string;
        };
        Update: {
          stt_minutes?: number;
          tts_minutes?: number;
          llm_input_tokens?: number;
          llm_output_tokens?: number;
          conversations_count?: number;
          total_speaking_time_minutes?: number;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          stripe_customer_id: string;
          stripe_subscription_id: string | null;
          plan: 'free' | 'starter' | 'pro' | 'unlimited';
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_customer_id: string;
          stripe_subscription_id?: string | null;
          plan?: 'free' | 'starter' | 'pro' | 'unlimited';
          status: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          stripe_subscription_id?: string | null;
          plan?: 'free' | 'starter' | 'pro' | 'unlimited';
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at?: string | null;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_level: 'beginner' | 'intermediate' | 'advanced';
      conversation_status: 'active' | 'completed' | 'archived';
      tip_category: 'grammar' | 'vocabulary' | 'pronunciation' | 'fluency' | 'general';
      subscription_plan: 'free' | 'starter' | 'pro' | 'unlimited';
    };
  };
}
